#!/usr/bin/env bash

# Run docker container if it's not up yet
if ! [[ $(docker ps | grep shlink_web_client_node) ]]; then
    docker compose up -d
fi

docker exec -it shlink_web_client_node /bin/sh -c "cd /home/shlink/www && $*"
