#!/bin/bash
set -e

echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

if [[ -z $TRAVIS_TAG ]]; then
  docker build -t shlinkio/shlink-web-client:latest .
  docker push shlinkio/shlink-web-client:latest
else
  docker build --build-arg VERSION=${TRAVIS_TAG#?} -t shlinkio/shlink-web-client:${TRAVIS_TAG#?} -t shlinkio/shlink-web-client:stable .
  docker push shlinkio/shlink-web-client:${TRAVIS_TAG#?}
  docker push shlinkio/shlink-web-client:stable
fi
