blank_issues_enabled: true
contact_links:
  - name: Question - Support
    about: Do you need help setting up or using shlink-web-client?
    url: https://github.com/orgs/shlinkio/discussions/new?category=help-wanted
