#!/bin/bash
set -ex

if [[ ${SOURCE_BRANCH} == 'master' ]]; then
    SHLINK_WEB_CLIENT_RELEASE='latest'
else
    SHLINK_WEB_CLIENT_RELEASE=${SOURCE_BRANCH#?}
fi

docker build --build-arg VERSION=${SHLINK_WEB_CLIENT_RELEASE} -t ${IMAGE_NAME} .
